//! Writing a mesh out as glTF (glb), OBJ, or PLY (ROADMAP-V2 4.3).
//!
//! All three carry per-vertex colour. glb keeps everything in one file, which
//! is what most viewers and engines want; OBJ is the interchange fallback and
//! writes colour as the three extra floats on each `v` line, which Blender,
//! MeshLab and CloudCompare all read.

use super::Mesh;
use std::fmt::Write as _;
use std::path::Path;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MeshFormat {
    Glb,
    Obj,
    Ply,
}

impl MeshFormat {
    pub fn parse(s: &str) -> Option<MeshFormat> {
        Some(match s.trim_start_matches('.').to_ascii_lowercase().as_str() {
            "glb" | "gltf" => MeshFormat::Glb,
            "obj" => MeshFormat::Obj,
            "ply" => MeshFormat::Ply,
            _ => return None,
        })
    }

    pub fn from_path(p: &Path) -> MeshFormat {
        p.extension()
            .and_then(|e| e.to_str())
            .and_then(MeshFormat::parse)
            .unwrap_or(MeshFormat::Glb)
    }

    pub fn extension(self) -> &'static str {
        match self {
            MeshFormat::Glb => "glb",
            MeshFormat::Obj => "obj",
            MeshFormat::Ply => "ply",
        }
    }
}

pub fn write(path: &Path, mesh: &Mesh, format: MeshFormat) -> Result<(), String> {
    if mesh.is_empty() {
        return Err("The mesh is empty, so there is nothing to write.".into());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let bytes = match format {
        MeshFormat::Glb => encode_glb(mesh)?,
        MeshFormat::Obj => encode_obj(mesh).into_bytes(),
        MeshFormat::Ply => encode_ply(mesh),
    };
    std::fs::write(path, bytes).map_err(|e| format!("Cannot write {}: {e}", path.display()))
}

fn colour_of(mesh: &Mesh, i: usize) -> [u8; 3] {
    if mesh.colors.len() == mesh.positions.len() {
        mesh.colors[i]
    } else {
        [200, 200, 200]
    }
}

/// Binary PLY with positions, normals, colours and triangle faces.
pub fn encode_ply(mesh: &Mesh) -> Vec<u8> {
    let mut out = Vec::new();
    let header = format!(
        "ply\nformat binary_little_endian 1.0\ncomment Generated by InstaSplatter\n\
         element vertex {}\nproperty float x\nproperty float y\nproperty float z\n\
         property float nx\nproperty float ny\nproperty float nz\n\
         property uchar red\nproperty uchar green\nproperty uchar blue\n\
         element face {}\nproperty list uchar int vertex_indices\nend_header\n",
        mesh.positions.len(),
        mesh.triangle_count()
    );
    out.extend_from_slice(header.as_bytes());
    for i in 0..mesh.positions.len() {
        for v in mesh.positions[i] {
            out.extend_from_slice(&v.to_le_bytes());
        }
        for v in mesh.normals[i] {
            out.extend_from_slice(&v.to_le_bytes());
        }
        out.extend_from_slice(&colour_of(mesh, i));
    }
    for t in mesh.indices.chunks_exact(3) {
        out.push(3u8);
        for &i in t {
            out.extend_from_slice(&(i as i32).to_le_bytes());
        }
    }
    out
}

/// Wavefront OBJ. Indices are one-based, and `v` carries colour after the
/// position, which is the widely-supported extension.
pub fn encode_obj(mesh: &Mesh) -> String {
    let mut s = String::with_capacity(mesh.positions.len() * 48);
    s.push_str("# Generated by InstaSplatter\n");
    for i in 0..mesh.positions.len() {
        let p = mesh.positions[i];
        let c = colour_of(mesh, i);
        let _ = writeln!(
            s,
            "v {} {} {} {:.6} {:.6} {:.6}",
            p[0],
            p[1],
            p[2],
            c[0] as f32 / 255.0,
            c[1] as f32 / 255.0,
            c[2] as f32 / 255.0
        );
    }
    for n in &mesh.normals {
        let _ = writeln!(s, "vn {} {} {}", n[0], n[1], n[2]);
    }
    for t in mesh.indices.chunks_exact(3) {
        let _ = writeln!(
            s,
            "f {}//{} {}//{} {}//{}",
            t[0] + 1,
            t[0] + 1,
            t[1] + 1,
            t[1] + 1,
            t[2] + 1,
            t[2] + 1
        );
    }
    s
}

fn align4(v: &mut Vec<u8>, pad: u8) {
    while v.len() % 4 != 0 {
        v.push(pad);
    }
}

/// Binary glTF 2.0. One buffer holds indices, positions, normals and colours;
/// the JSON chunk describes where each lives.
pub fn encode_glb(mesh: &Mesh) -> Result<Vec<u8>, String> {
    let n = mesh.positions.len();
    if n > u32::MAX as usize {
        return Err("The mesh has too many vertices for glTF.".into());
    }

    // ---- Binary payload ---------------------------------------------------
    let mut bin: Vec<u8> = Vec::new();

    let idx_offset = bin.len();
    for &i in &mesh.indices {
        bin.extend_from_slice(&i.to_le_bytes());
    }
    let idx_len = bin.len() - idx_offset;

    let pos_offset = bin.len();
    let mut min = [f32::INFINITY; 3];
    let mut max = [f32::NEG_INFINITY; 3];
    for p in &mesh.positions {
        for k in 0..3 {
            min[k] = min[k].min(p[k]);
            max[k] = max[k].max(p[k]);
            bin.extend_from_slice(&p[k].to_le_bytes());
        }
    }
    let pos_len = bin.len() - pos_offset;

    let nrm_offset = bin.len();
    for v in &mesh.normals {
        for k in 0..3 {
            bin.extend_from_slice(&v[k].to_le_bytes());
        }
    }
    let nrm_len = bin.len() - nrm_offset;

    // COLOR_0 as normalized unsigned bytes, four per vertex so each element
    // is already four-byte aligned.
    let col_offset = bin.len();
    for i in 0..n {
        let c = colour_of(mesh, i);
        bin.extend_from_slice(&[c[0], c[1], c[2], 255]);
    }
    let col_len = bin.len() - col_offset;

    let json = format!(
        r#"{{"asset":{{"version":"2.0","generator":"InstaSplatter"}},"scene":0,"scenes":[{{"nodes":[0]}}],"nodes":[{{"mesh":0}}],"meshes":[{{"primitives":[{{"attributes":{{"POSITION":1,"NORMAL":2,"COLOR_0":3}},"indices":0,"mode":4}}]}}],"buffers":[{{"byteLength":{bin_len}}}],"bufferViews":[{{"buffer":0,"byteOffset":{idx_offset},"byteLength":{idx_len},"target":34963}},{{"buffer":0,"byteOffset":{pos_offset},"byteLength":{pos_len},"target":34962}},{{"buffer":0,"byteOffset":{nrm_offset},"byteLength":{nrm_len},"target":34962}},{{"buffer":0,"byteOffset":{col_offset},"byteLength":{col_len},"target":34962}}],"accessors":[{{"bufferView":0,"componentType":5125,"count":{icount},"type":"SCALAR"}},{{"bufferView":1,"componentType":5126,"count":{n},"type":"VEC3","min":[{minx},{miny},{minz}],"max":[{maxx},{maxy},{maxz}]}},{{"bufferView":2,"componentType":5126,"count":{n},"type":"VEC3"}},{{"bufferView":3,"componentType":5121,"normalized":true,"count":{n},"type":"VEC4"}}]}}"#,
        bin_len = bin.len(),
        icount = mesh.indices.len(),
        minx = min[0],
        miny = min[1],
        minz = min[2],
        maxx = max[0],
        maxy = max[1],
        maxz = max[2],
    );

    let mut json_chunk = json.into_bytes();
    align4(&mut json_chunk, b' '); // JSON pads with spaces
    align4(&mut bin, 0); // BIN pads with zeros

    let total = 12 + 8 + json_chunk.len() + 8 + bin.len();
    let mut out = Vec::with_capacity(total);
    out.extend_from_slice(b"glTF");
    out.extend_from_slice(&2u32.to_le_bytes());
    out.extend_from_slice(&(total as u32).to_le_bytes());
    out.extend_from_slice(&(json_chunk.len() as u32).to_le_bytes());
    out.extend_from_slice(b"JSON");
    out.extend_from_slice(&json_chunk);
    out.extend_from_slice(&(bin.len() as u32).to_le_bytes());
    out.extend_from_slice(b"BIN\0");
    out.extend_from_slice(&bin);
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tri() -> Mesh {
        let mut m = Mesh {
            positions: vec![[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 2.0, 0.0]],
            normals: Vec::new(),
            colors: vec![[255, 0, 0], [0, 255, 0], [0, 0, 255]],
            indices: vec![0, 1, 2],
        };
        m.recompute_normals();
        m
    }

    #[test]
    fn formats_come_from_the_extension_and_default_to_glb() {
        assert_eq!(MeshFormat::from_path(Path::new("a.obj")), MeshFormat::Obj);
        assert_eq!(MeshFormat::from_path(Path::new("a.PLY")), MeshFormat::Ply);
        assert_eq!(MeshFormat::from_path(Path::new("a.glb")), MeshFormat::Glb);
        assert_eq!(MeshFormat::from_path(Path::new("a.weird")), MeshFormat::Glb);
        assert_eq!(MeshFormat::parse("gltf"), Some(MeshFormat::Glb));
        assert_eq!(MeshFormat::parse("stl"), None);
    }

    #[test]
    fn an_empty_mesh_is_refused_rather_than_written() {
        let dir = std::env::temp_dir().join("instasplatter_mesh_empty");
        let _ = std::fs::create_dir_all(&dir);
        let p = dir.join("x.glb");
        assert!(write(&p, &Mesh::default(), MeshFormat::Glb).is_err());
        assert!(!p.exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn obj_has_one_line_per_vertex_normal_and_face() {
        let s = encode_obj(&tri());
        assert_eq!(s.lines().filter(|l| l.starts_with("v ")).count(), 3);
        assert_eq!(s.lines().filter(|l| l.starts_with("vn ")).count(), 3);
        assert_eq!(s.lines().filter(|l| l.starts_with("f ")).count(), 1);
        // One-based indices.
        assert!(s.contains("f 1//1 2//2 3//3"));
        // Colour rides along on the vertex line.
        let v0 = s.lines().find(|l| l.starts_with("v ")).unwrap();
        assert!(v0.ends_with("1.000000 0.000000 0.000000"), "{v0}");
    }

    #[test]
    fn ply_declares_its_counts_and_carries_every_vertex() {
        let m = tri();
        let bytes = encode_ply(&m);
        let text = String::from_utf8_lossy(&bytes[..bytes.len().min(400)]);
        assert!(text.contains("element vertex 3"));
        assert!(text.contains("element face 1"));

        let header_end = bytes
            .windows(11)
            .position(|w| w == b"end_header\n")
            .unwrap()
            + 11;
        // 3 vertices * (3+3 floats + 3 bytes) + 1 face * (1 + 3*4 bytes)
        let expect = 3 * (6 * 4 + 3) + (1 + 12);
        assert_eq!(bytes.len() - header_end, expect);
    }

    #[test]
    fn glb_has_a_valid_container_and_its_chunks_line_up() {
        let bytes = encode_glb(&tri()).unwrap();
        assert_eq!(&bytes[0..4], b"glTF");
        assert_eq!(u32::from_le_bytes(bytes[4..8].try_into().unwrap()), 2);
        assert_eq!(
            u32::from_le_bytes(bytes[8..12].try_into().unwrap()) as usize,
            bytes.len(),
            "declared length must match the file"
        );

        let json_len = u32::from_le_bytes(bytes[12..16].try_into().unwrap()) as usize;
        assert_eq!(&bytes[16..20], b"JSON");
        assert_eq!(json_len % 4, 0, "JSON chunk must be 4-byte aligned");
        let json = std::str::from_utf8(&bytes[20..20 + json_len]).unwrap();

        let bin_start = 20 + json_len;
        let bin_len = u32::from_le_bytes(bytes[bin_start..bin_start + 4].try_into().unwrap()) as usize;
        assert_eq!(&bytes[bin_start + 4..bin_start + 8], b"BIN\0");
        assert_eq!(bin_len % 4, 0);
        assert_eq!(bin_start + 8 + bin_len, bytes.len());

        // The JSON parses, and its buffer length matches the BIN chunk.
        let v: serde_json::Value = serde_json::from_str(json.trim_end()).expect("invalid JSON");
        assert_eq!(v["buffers"][0]["byteLength"].as_u64().unwrap() as usize, bin_len);
        assert_eq!(v["accessors"][0]["count"].as_u64().unwrap(), 3);
        assert_eq!(v["accessors"][1]["count"].as_u64().unwrap(), 3);
        assert_eq!(v["accessors"][1]["max"][1].as_f64().unwrap(), 2.0);

        // Every buffer view sits inside the buffer.
        for bv in v["bufferViews"].as_array().unwrap() {
            let off = bv["byteOffset"].as_u64().unwrap() as usize;
            let len = bv["byteLength"].as_u64().unwrap() as usize;
            assert!(off + len <= bin_len, "buffer view {off}+{len} overruns {bin_len}");
        }
    }

    #[test]
    fn glb_indices_round_trip_through_the_binary_chunk() {
        let m = tri();
        let bytes = encode_glb(&m).unwrap();
        let json_len = u32::from_le_bytes(bytes[12..16].try_into().unwrap()) as usize;
        let bin = &bytes[20 + json_len + 8..];
        let read: Vec<u32> = bin[..12]
            .chunks_exact(4)
            .map(|c| u32::from_le_bytes(c.try_into().unwrap()))
            .collect();
        assert_eq!(read, m.indices);
    }

    #[test]
    fn a_mesh_without_colours_still_writes() {
        let mut m = tri();
        m.colors.clear();
        assert!(encode_glb(&m).is_ok());
        assert!(encode_obj(&m).contains("v 0 0 0"));
        assert!(!encode_ply(&m).is_empty());
    }
}
